import {
  fortnite,
  cod,
  fifa23,
  leagueOfLegends,
  pubg,
  counterStrike,
  overwatch,
  dota,
} from '../assets';

export const featured = [
  {
    id: 1,
    title: 'League of Legends',
    deadline: 'Registration ends 30th Jan 2023',
    link: '/',
    price: 1200,
    image: leagueOfLegends,
  },
  {
    id: 2,
    title: 'Fortnite BoxFight Winter',
    deadline: 'Registration starts 30th Jan 2023',
    link: '/',
    price: 1200,
    image: fortnite,
  },
  {
    id: 3,
    title: 'Dota 2',
    deadline: 'Registration starts 30th Jan 2023',
    link: '/',
    price: 900,
    image: dota,
  },
  {
    id: 4,
    title: 'Call of Duty',
    deadline: 'Registration ends 30th Jan 2023',
    link: '/',
    price: 1200,
    image: cod,
  },
  {
    id: 5,
    title: 'PUBG: Battlegrounds',
    deadline: 'Registration ends 30th Jan 2023',
    link: '/',
    price: 1000,
    image: pubg,
  },
  {
    id: 6,
    title: 'FIFA 2023',
    deadline: 'Registration ends 30th Jan 2023',
    link: '/',
    price: 1200,
    image: fifa23,
  },
  {
    id: 7,
    title: 'Counter Strike',
    deadline: 'Registration ends 30th Jan 2023',
    link: '/',
    price: 1000,
    image: counterStrike,
  },
  {
    id: 8,
    title: 'Overwatch 2',
    deadline: 'Registration ends 30th Jan 2023',
    link: '/',
    price: 1000,
    image: overwatch,
  },
];
